instagram/django_app/instagram/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


apis_patterns = [
    url(r'^photo/', include('photo.urls.apis')),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(apis_patterns)),

    url(r'^photo/', include('photo.urls.views', namespace='photo')),
    url(r'^member/', include('member.urls', namespace='member')),
    # url(r'^auth/', include('django.contrib.auth.urls', namespace='auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/django_app/member/urls.py
from django.conf.urls import url
from member import views


urlpatterns = [
    url(r'login/$', views.MemberLogin.as_view(), name="login"),
    url(r'signup/$', views.MemberSignup.as_view(), name="signup"),
    url(r'logout/$', views.LogoutView.as_view(), name="logout"),
]

instagram/django_app/photo/urls/views.py
from django.conf.urls import url
from .. import views

urlpatterns = [
    # url(r'^photo/$', views.photo_list, name='photo_list'),
    url(r'^photo_list/$', views.PhotoList.as_view(), name='photo_list'),
    url(r'^photo_add/$', views.PhotoAdd.as_view(), name='photo_add'),
    url(r'^photo_detail/(?P<pk>\d+)/$', views.PhotoDetail.as_view(), name='photo_detail'),
    url(r'^photo/delete/$', views.photo_delete, name='photo_delete'),
]

instagram/django_app/templates/common/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <title>신난다!</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a href="" class="navbar-brand">콜라보 테스트!</a>
        </div>

        <div class="collapse navbar-collapse" id="main-navbar">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'photo:photo_list' %}">Photo</a>
                    </li>

                    <li>
                        <a href="{% url 'member:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'member:signup' %}">SignUp</a>
                    </li>
                    <li>
                        <a href="{% url 'member:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block login %}
{% endblock %}
{% if user.is_authenticated %}
    {% block content %}
    {% endblock %}
{% else %}
    <h3>로그인 하세요</h3>
{% endif %}
</body>
</html>